name: El Flecha Negra
url: https://elflechanegra.com/
permalink: pretty
debug: false
development: false

markdown: kramdown
redcarpet:
  extensions: ["smart"]

highlighter: rouge
exclude: [README.md, config.rb, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, ".vendor", update]

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
collections:
  videos:
    output: false
  events:
    output: false
  bios:
    output: true
    permalink: /bios/:name

# Google Analytics tracking ID.
ga: 'UA-432773-17'
