name: El Flecha Negra
permalink: pretty
debug: false
development: false

markdown: redcarpet
redcarpet:
  extensions: ["smart"]

highlighter: pygments
exclude: [README.md, config.rb, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, ".vendor"]

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
collections:
  videos:
    output: false
  events:
    output: false

# Google Analytics tracking ID.
ga: 'UA-432773-17'
